version: 2
jobs:
  build:
    working_directory: ~/Projects/improvisor
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo apt-get install portaudio19-dev
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
             . venv/bin/activate
             python -m unittest discover -v
